### ISSUE TITLE
How to get HTTP request when serving HTTP?

### ISSUE THREAD

**Issue by sokolas** [probable-basilisk/pollnet#19]
This is not actually an issue, but a request for documentation/example.
Is it possible to access HTTP request data when serving HTTP?

**Comment by probable-basilisk** [comment]
No, the HTTP server is very bare-bones at the moment, it only serves static content either from real files or from memory, and you don't get any control/information about individual requests it serves.

Putting in a dynamic HTTP server mode (where you would directly respond to requests) is something I've thought about, but it might also be simpler to just write a minimal HTTP 1.1 server on top of TCP.
