### ISSUE TITLE
Can't seem to get a status code from an http GET

### ISSUE THREAD

**Issue by Thial** [probable-basilisk/pollnet#9]
Hello,

I have followed the examples which state that for example an http get should contain 2 messages, one being the status code and the other being the body.

I was trying to get a file from github but the body arrives as the first message. I have tried to wait until more messages arrive as well to see if the order is not flipped but on the second poll call the socket is already closed. Tested even without any manual socket closing and just looping poll on each game tick to see what it receives and the only thing I ever receive is just the body.

Am I missing something or is there currently no way to get an http status code ?

Thanks in advance.

**Comment by probable-basilisk** [comment]
Ok yeah it seems that while I had maybe intended for it to work that way, in actuality only the body was being returned. In this latest release (0.6.0) http GET and POST take an argument indicating whether to return only the body, or whether to return status->headers->body as three sequential results.

**Comment by probable-basilisk** [comment]
Works+tested in 1.0.0.
